apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-serverwork
  labels:
    app: git-serverwork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-serverwork
  template:
    metadata:
      labels:
        app: git-serverwork
    spec:
      nodeSelector:
        node-type: k8sworker
      containers:
        - name: git-server1
          image: RRR/rrr:ttt
          command: ["sh", "-c", "redis-server --daemonize yes && java -jar app.jar"]
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: git-serverwork
  labels:
    app: git-serverwork
spec:
  type: NodePort
  ports:
    - name: git-work
      protocol: TCP
      port: 8080
  selector:
    app: git-serverwork
