apiVersion: apps/v1
kind: Deployment
metadata:
  name: em-git-communication
  labels:
    app: em-git-communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: em-git-communication
  template:
    metadata:
      labels:
        app: em-git-communication
    spec:
      containers:
      - name: em-git-communication
        image: RRR/rrr:ttt
        command: [ "npm", "run", "server"]
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: em-git-communication
spec:
  type: NodePort
  selector:
    app: em-git-communication
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30042
