apiVersion: apps/v1
kind: Deployment
metadata:
  name: em-git-gateway
  labels:
    app: em-git-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: em-git-gateway
  template:
    metadata:
      labels:
        app: em-git-gateway
    spec:
      containers:
      - name: em-git-gateway
        image: RRR/rrr:ttt
        command: [ "npm", "run", "server"]
        ports:
        - containerPort: 8383
---
apiVersion: v1
kind: Service
metadata:
  name: em-git-gateway
spec:
  type: NodePort
  selector:
    app: em-git-gateway
  ports:
    - protocol: TCP
      port: 8383
