apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-serverown-dev
  labels:
    app: git-serverown-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: git-serverown-dev
  template:
    metadata:
      labels:
        app: git-serverown-dev
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8sworker          
#        node-type: k8sworker
      containers:
        - name: git-server1
          image:  RRR/rrr:ttt
          command: ["sh", "-c", "/app/script.sh"]
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
          - mountPath: /mnt/git
            name: git-data
      volumes:
      - name: git-data
        persistentVolumeClaim:
          claimName: gitown-pv-volume-dev
---
apiVersion: v1
kind: Service
metadata:
  name: git-serverown
  labels:
    app: git-serverown-dev
spec:
  type: NodePort
  ports:
    - name: git-java
      protocol: TCP
      port: 8082
    - name: git-server
      protocol: TCP
      port: 3000
  selector:
    app: git-serverown-dev
