apiVersion: apps/v1
kind: Deployment
metadata:
  name: em-iam-service
  labels:
    app: em-iam-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: em-iam-service
  template:
    metadata:
      labels:
        app: em-iam-service
    spec:
      containers:
      - name: em-iam-service
        image: RRR/rrr:ttt
        command: [ "npm", "run", "server"]
        ports:
        - containerPort: 8282
---
apiVersion: v1
kind: Service
metadata:
  name: em-iam-service
spec:
  type: NodePort
  selector:
    app: em-iam-service
  ports:
    - protocol: TCP
      port: 8282
      nodePort: 30043
