apiVersion: apps/v1
kind: Deployment
metadata:
  name: em-rendering-service
  labels:
    app: em-rendering-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: em-rendering-service
  template:
    metadata:
      labels:
        app: em-rendering-service
    spec:
      containers:
      - name: em-rendering-service
        image: RRR/rrr:ttt
        command: [ "npm", "run", "server"]
        ports:
        - containerPort: 8484
        readinessProbe:
          httpGet:
            path: /
            port: 8484
        livenessProbe:
          httpGet:
            path: /
            port: 8484
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: em-rendering-service
spec:
  type: NodePort
  selector:
    app: em-rendering-service
  ports:
    - protocol: TCP
      port: 8484
